services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    Seefahrer\GuestBookBundle:
        autowire: true
        autoconfigure: true
        public: true
        arguments:
            - '@contao.routing.scope_matcher'